### ISSUE TITLE
CSC : error CS1617: Invalid option '9' for /langversion. Use '/langversion:?' to list supported values.

### ISSUE THREAD

**Issue by plantematthieu** [RWS/Sdl-Community#761]
Hi, 

I'm trying to build the DeepLMTProvider but I got this issue.
I'm using Visual Studio 2017 and my target framework is .NET Framework 4.8.

Thanks for your help.

Matthieu

**Comment by RainerLeukel** [comment]
Hi,

you have to use Visual Studio 2019 for using C#9 syntax.

See also: https://github.com/dotnet/roslyn/issues/21783#issuecomment-327395016

Or you re-code the incompatible parts so that they are compatible with your Visual Studio 2017 C#7 version.

Regards
Rainer

**Comment by plantematthieu** [comment]
Thanks RainerLeukel, it worked! 
I also had to change the langversion manually in the .csproj file
